### ISSUE TITLE
Error converting mkv to sup

### ISSUE THREAD

**Issue by ReggaeUlli** [Jsakkos/mkv-episode-matcher#11]
Attached is the std out copied into a text file. The Error Occurs when converting a mkv to a sup file. I think this is the most important part of the Log. It says that there was invalid data given to the muxer. As the file plays without a problem in VLC and i can also switch on the subtitles etc, any idea how i could find the cause for this?
[STDOUT.txt](https://github.com/user-attachments/files/17244719/STDOUT.txt)
> Stream #0:0(eng): Subtitle: dvd_subtitle, 720x576
>       Metadata:
>         BPS-eng         : 7847
>         DURATION-eng    : 00:19:49.831466666
>         NUMBER_OF_FRAMES-eng: 372
>         NUMBER_OF_BYTES-eng: 1167104
>         SOURCE_ID-eng   : 0120BD
>         _STATISTICS_WRITING_APP-eng: MakeMKV v1.17.8 win(x64-release)
>         _STATISTICS_WRITING_DATE_UTC-eng: 2024-10-01 11:58:25
>         _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
> Press [q] to stop, [?] for help
> [sup @ 00000266a7c7d380] Not enough data, skipping 2032 bytes
> [sost#0:0/copy @ 00000266a7c7aa00] Error submitting a packet to the muxer: Invalid data found when processing input
>     Last message repeated 1 times
> [out#0/sup @ 00000266a7c7fdc0] Error muxing a packet
> [out#0/sup @ 00000266a7c7fdc0] Task finished with error code: -1094995529 (Invalid data found when processing input)
> [out#0/sup @ 00000266a7c7fdc0] Terminating thread with return code -1094995529 (Invalid data found when processing input)
> [out#0/sup @ 00000266a7c7fdc0] video:0KiB audio:0KiB subtitle:2KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
> size=       0KiB time=00:00:25.03 bitrate=   0.0kbits/s speed= 711x
> Conversion failed!
> 2024-10-03 15:06:52.091 | ERROR    | mkv_episode_matcher.mkv_to_srt:convert_mkv_to_sup:47 - Error converting Scrubs\Season 2\test (9).mkv: Command '['ffmpeg', '-i', 'Scrubs\\Season 2\\test (9).mkv', '-map', '0:s:0', '-c', 'copy', 'Scrubs\\Season 2\\ocr\\test (9).sup']' returned non-zero exit status 3199971767.

**Comment by Jsakkos** [comment]
Is this a BluRay disc or DVD? I don't think the code has ever been tested on DVDs.

**Comment by ReggaeUlli** [comment]
Yes it was a dvd, that explains it, thank you! If i get it working i will open a PR.

**Comment by Jsakkos** [comment]
@ReggaeUlli Give the latest version a try, as it uses speech to text by default.

**Comment by ReggaeUlli** [comment]
@Jsakkos Works like a charm, thank you!
