### ISSUE TITLE
Mix of Empty & Non-Empty Folders

### ISSUE THREAD

**Issue by iokevins** [Jsakkos/mkv-episode-matcher#12]
In function \mkv_episode_matcher\episode_matcher.py::process_show(...), it seems the loop logic to populate list "mkv_files" might need enhancement to support folder structures with a mix of empty & non-empty folders (?)

E.g., if I have this folder structure, it seems to detect the MKV files in directory Season 1, but the list gets re-initialized to empty after traversing the subsequent empty folders--the process reports "No new files to process":

Show 
-   Season 1 (Non-Empty)
-   Season 2 (Empty)
-   Season 3 (Empty)

Thank you

**Comment by Jsakkos** [comment]
@iokevins That certainly seems like a bug. I'll take a look when I have some time. Feel free to submit a pull request if you're able to resolve the issue.
